darwinfroese/hacksite

- .vscode/settings.json
- contributing.md
Added contributing.md
@darwinfroese
> added contributing

- .circleci/config.yml
> setting up circleci

- webclient/src/components/elements/Project.vue
As requested in #19 a prompt requesting user confirmation was added when deleting a project.
@codeb9
> Add confirmation when deleting a project

- .gitignore
- server/models/models.go
- server/pkg/accounts/accounts.go
- server/pkg/api/accountHandlers.go
- server/pkg/auth/login.go
- server/pkg/database/boltDB.go
- server/pkg/database/database.go
- webclient/package.json
- webclient/src/components/views/CreateAccount.vue
- webclient/src/database.js
- webclient/src/router/index.js
- webclient/yarn.lock
I created the server side validation logic for checking if a username and email already exists by making a copy of the "GetAccount" method with "GetAccountByEmail" making the checks and sending error messages to the client. 
Also... I added a new Vue library called [Vee-Validate ](http://vee-validate.logaretm.com/index.html#about) to do client side validation of the fields and updated the CreateAccount.Vue file .
Some talking points... I'm a total golang noob => if anything in the code seems strange or doesn't make sense, assume I have no idea what I am doing. I come from a NodeJs // PHP background looking to get a "real" server-side language under my belt.
Be sure to run a `yarn install` to get the new Vue package
@darwinfroese
> Outridair 1

- server/pkg/api/projectHandlers.go
- server/pkg/auth/auth_test.go
- server/pkg/projects/projects.go
- server/pkg/projects/projects_test.go
- server/pkg/projects/validator_test.go
- Added unit tests to the projects package
- fixed bugs in project deletion
- made all project calls order their params the same
- hid addProjectToUser function
- removeIDFromProjectList had index and id values flipped
- Removing the project removed it from the accounts project list but didn't update the account in the database
> Projects refactor

- server/models/models.go
- server/pkg/accounts/accounts.go
- server/pkg/accounts/accounts_test.go
- server/pkg/database/boltDB.go
- server/pkg/iterations/iterations.go
- server/pkg/iterations/iterations_test.go
- server/pkg/projects/projects_test.go
- fixed unit tests
- fixed some bad decisions i made regarding error message output
> unit tests

- server/pkg/projects/projects.go
- server/pkg/tasks/tasks.go
Summary of the changes made
Any notes that need to have attention drawn to them
@darwinfroese
> fixed bug with projects not updating with correct project ID

- server/pkg/projects/projects.go
- server/pkg/tasks/tasks.go
- server/pkg/tasks/tasks_test.go
> Task update fix

- server/cmd/server.go
- server/pkg/accounts/accounts_test.go
- server/pkg/api/accountHandlers.go
- server/pkg/api/apiUtils.go
- server/pkg/api/authenticationHandlers.go
- server/pkg/api/context.go
- server/pkg/api/iterationHandlers.go
- server/pkg/api/middleware.go
- server/pkg/api/projectHandlers.go
- server/pkg/api/routes.go
- server/pkg/api/sessionHandlers.go
- server/pkg/api/taskHandlers.go
- server/pkg/api/utilHandlers.go
- server/pkg/api/utils.go
- server/pkg/auth/auth.go
- server/pkg/auth/auth_test.go
- server/pkg/database/bolt/boltDB.go
- server/pkg/database/database.go
- server/pkg/iterations/iterations_test.go
- server/pkg/projects/projects.go
- server/pkg/projects/projects_test.go
- server/pkg/scheduler/scheduler.go
- server/pkg/scheduler/sessions_test.go
- server/pkg/tasks/tasks_test.go
Summary of the changes made
Any notes that need to have attention drawn to them
@darwinfroese
> Context handlers middleware

- environments/dev.env.json
- environments/test.env.json
- server/cmd/server.go
- server/models/models.go
- server/pkg/accounts/accounts.go
- server/pkg/accounts/accounts_test.go
- server/pkg/api/projectHandlers.go
- server/pkg/auth/auth.go
- server/pkg/auth/auth_test.go
- server/pkg/auth/login.go
- server/pkg/auth/login_test.go
- server/pkg/aws/aws.go
- server/pkg/config/config.go
- server/pkg/database/bolt/boltDB.go
- server/pkg/database/database.go
- server/pkg/database/dynamo/dynamo.go
- server/pkg/iterations/iterations_test.go
- server/pkg/log/logrus/logrus.go
- server/pkg/projects/projects.go
- server/pkg/projects/projects_test.go
- server/pkg/scheduler/sessions_test.go
- server/pkg/tasks/tasks_test.go
- webclient/src/components/elements/InfoFooter.vue
- webclient/src/components/views/Details.vue
- webclient/src/components/views/Login.vue
- webclient/src/router/index.js
- refactored DB to work better with dynamo
- implemented dynamo adapter
- display message about migration to dynamo
- all boltdb functionality replicated in Dynamo
* dynamo db doesn't have auto incrementing ids so we need to switch to something else, using uuids instead that are randomly generated when needed
@darwinfroese
> updated DB interface; started aws

- webclient/src/components/elements/InfoFooter.vue
- webclient/src/components/views/ReleaseNotes.vue
- webclient/src/router/index.js
Summary of the changes made
Any notes that need to have attention drawn to them
@darwinfroese
> added release notes component

- server/models/models.go
- server/pkg/accounts/accounts_test.go
Include name as part of the model
Fixes https://github.com/darwinfroese/hacksite/issues/67
@darwinfroese
> Issue 67 add account name

- server/pkg/api/authenticationHandlers.go
> added POST method for login with rememberMe in body

- server/models/account.go
- server/models/error.go
- server/models/models.go
- server/models/project.go
- server/pkg/accounts/accounts.go
- server/pkg/accounts/accounts_test.go
- server/pkg/api/accountHandlers.go
- server/pkg/evolutions/evolutions.go
- server/pkg/evolutions/evolutions_test.go
- server/pkg/projects/projects.go
- server/pkg/projects/projects_test.go
- server/pkg/tasks/tasks_test.go
- webclient/src/components/views/CreateAccount.vue
- Models have separate files where needed
- Created api responses to hide error messages where needed
- These will be useful in the future
- Changed how message is rendered
- Hid more things that need to be hidden
Resolves #63 
@darwinfroese
> refactored models package and cascaded changes

- server/pkg/projects/projects.go
- server/pkg/tasks/tasks_test.go
- Complete iteration, swaps to the next non-completed if it exists
- A project with more than one evolution is marked as "InProgress" even if the current evolution has no completed tasks
Completes #18
@darwinfroese
> swap to next iteration if it exists

- server/cmd/server.go
- server/pkg/api/middleware.go
- server/pkg/api/routes.go
- server/pkg/api/statusWriter.go
- server/pkg/api/utilHandlers.go
> Wrapped ResponseWriter

- server/pkg/accounts/accounts.go
- server/pkg/accounts/accounts_test.go
- server/pkg/api/accountHandlers.go
- server/pkg/api/authenticationHandlers.go
- server/pkg/auth/auth.go
- server/pkg/database/bolt/boltDB.go
- server/pkg/database/database.go
- server/pkg/database/dynamo/dynamo.go
Account Endpoint:
- Get account info for currently logged in account
- Update existing account information
- Account usernames are case-insensitive
> get account; update account; case-insensitive usernames;

- webclient/src/components/views/ReleaseNotes.vue
> i59: updated release notes

- server/pkg/api/accountHandlers.go
- webclient/src/components/views/CreateAccount.vue
- webclient/src/components/views/Login.vue
- removed extra print in accountsHandler.go
- spinner disables in all return cases on create account
- prints success message on succesful account creation
- removed login page message
Closes #93
> i93: fixed create account bugs

- README.md
- server/cmd/server.go
- server/models/account.go
- server/models/error.go
- server/models/models.go
- server/models/project.go
- server/pkg/accounts/accounts.go
- server/pkg/accounts/accounts_test.go
- server/pkg/api/accountHandlers.go
- server/pkg/api/authenticationHandlers.go
- server/pkg/api/middleware.go
- server/pkg/api/projectHandlers.go
- server/pkg/api/routes.go
- server/pkg/api/statusWriter.go
- server/pkg/api/utilHandlers.go
- server/pkg/auth/auth.go
- server/pkg/database/bolt/boltDB.go
- server/pkg/database/database.go
- server/pkg/database/dynamo/dynamo.go
- server/pkg/evolutions/evolutions.go
- server/pkg/evolutions/evolutions_test.go
- server/pkg/projects/projects.go
- server/pkg/projects/projects_test.go
- server/pkg/tasks/tasks_test.go
- webclient/src/components/views/Create.vue
- webclient/src/components/views/CreateAccount.vue
- webclient/src/components/views/Login.vue
- webclient/src/components/views/ReleaseNotes.vue
- webclient/src/database.js
- updated project validation
- updated account validation
- updated validation tests
- `post` login instead of `get` login
closes #77
> Validation updates
